name: Build and deploy Node.js app to Azure Web App - cloudproject-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4  # Checkout the code from the repository

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'  # Set Node.js version based on your requirement

      - name: Navigate to backend directory and install dependencies
        run: |
          cd frontend/backend  # Navigate to the backend directory (adjust path as needed)
          npm install  # Install the backend dependencies

      - name: Test and build (if applicable)
        run: |
          cd frontend/backend  # Ensure you're in the backend directory
          npm run test --if-present  # Run tests if defined (optional)
          npm run build --if-present  # Run build if defined (optional)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app  # Name of the artifact
          path: frontend/backend  # Path to the backend folder

  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu agents for deployment
    needs: build  # This job will run after the build job is complete
    environment:
      name: 'Production'  # Define environment as 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}  # Output URL of the deployed web app

    permissions:
      id-token: write  # Required for requesting the JWT (for authentication)
      contents: read  # Required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app  # Download the artifact uploaded in the build job

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C41E4BA2A811415283CE466B095ADF40 }}  # Replace with your actual secret
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4BBEDB7634ED4857BB64C4BD271C9EDB }}  # Replace with your actual secret
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ED5690EDB10946DB8574AD2E51E27D63 }}  # Replace with your actual secret

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'cloudproject-backend'  # Replace with your Azure Web App name
          slot-name: 'Production'  # You can use 'staging' if you want to deploy to a staging slot
          package: .  # Path to the backend app (ensure correct directory)
      
      - name: Start Node.js server
        run: |
          cd frontend/backend  # Ensure we are in the backend directory
          npm start  # Start the Node.js server (runs node index.js)

